x

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,6 +1,13 @@
 #!/bin/sh
 
- "C:\Program Files\Git\bin\bash.exe" -i -c $0/../pre-commit.sh --window full --needs-console
+if ! command -v pwsh &> /dev/null
+then
+    echo "Powershell not found. Will be installed..."
+    dotnet tool update --global PowerShell
+fi
+
+"C:\Users\tftom\.dotnet\tools\pwsh.exe" -c Start-Process "C:\Users\tftom\.dotnet\tools\pwsh.exe" $0/../pre-commit.ps1 -PassThru -Wait
+# "C:\Program Files\Git\bin\bash.exe" -i -c $0/../pre-commit.sh --window full --needs-console
 # "C:\Program Files\Git\git-bash.exe"  -c $0/../pre-commit.sh --needs-console
 
 
